config/routes.rb
require "monban/constraints/signed_in"


Rails.application.routes.draw do
  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end


  root "homes#show"

  resources :text_shouts, only: [:create]
  resources :photo_shouts, only: [:create]
  resource :search, only: [:show]

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show] do 
    member do 
      post "follow" => "following_relationships#create"
      delete "unfollow" => "following_relationships#destroy"
    end
  end
end

app/models/following_relationship.rb
class FollowingRelationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed_user, class_name: "User"
end

app/models/photo_shout.rb
class PhotoShout < ActiveRecord::Base
  has_attached_file :image 
  validates_attachment_content_type :image, :content_type => /\Aimage/
end

app/models/shout.rb
class Shout < ActiveRecord::Base
  belongs_to :user
  belongs_to :content, polymorphic: true   

  def self.search(query)
    text_shout_ids = TextShout.where("body ILIKE ?", "%#{@query}%").map(&:id)
    where(id: text_shout_ids)
  end
end

app/models/text_shout.rb
class TextShout < ActiveRecord::Base
  has_one :shout, as: :content
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  has_many :shouts

  has_many :followed_user_relationships,
           class_name: "FollowingRelationship",
           foreign_key: :follower_id

  has_many :followed_users, through: :followed_user_relationships

  has_many :follower_relationships,
           class_name: "FollowingRelationship",
           foreign_key: :followed_user_id

  has_many :followers, through: :follower_relationships

  def timeline
    Shout.where(user_id: self_and_followed_user_ids + followed_user_ids).order(created_at: :desc)
  end

  def follow(user)
    followed_users << user
  end

  def unfollow(user)
    followed_users.delete(user)
  end

  def following?(user)
    followed_users.include?(user)
  end

  def to_param
    username
  end

  private

  def self_and_followed_user_ids
    [id] + followed_user_ids
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController 
  
  def show
    @text_shout = TextShout.new 
    @photo_shout = PhotoShout.new
    @timeline = current_user.timeline.page(params[:page]).per(2) 
  end
end 

app/controllers/following_relationships_controller.rb
class FollowingRelationshipsController < ApplicationController 
  def create 
    user = User.find_by!(username: params[:id])
    current_user.follow(user)
    redirect_to user 
  end


  def destroy
    user = find_user
    current_user.unfollow(user)
    redirect_to user
  end

  private

  def find_user
    User.find_by!(username: params[:id])
  end
end 

app/controllers/homes_controller.rb
class HomesController < ApplicationController 
  def show 
    @user = User.new 
  end 
end 

app/controllers/photo_shouts_controller.rb
class PhotoShoutsController < ApplicationController
  def create
    photo_shout = PhotoShout.new(photo_shout_params)
    current_user.shouts.create(content: photo_shout)
    redirect_to dashboard_path
  end

  private

  def photo_shout_params
    params.require(:photo_shout).permit(:image)
  end
end 

app/controllers/searches_controller.rb
class SearchesController < ApplicationController 

  def show
    @query = params[:search][:query]
    @results = Shout.search(@query)
  end

end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController 
  def create
    current_user.shouts.create(shout_params)
    redirect_to dashboard_path 
  end

  private

  def shout_params
    params.require(:shout).permit(:content)
  end 
end

app/controllers/text_shouts_controller.rb
class TextShoutsController < ApplicationController 
  def create
    text_shout = TextShout.new(text_shout_params)
    current_user.shouts.create(content: text_shout)
    redirect_to  dashboard_path  
  end

  private 

  def text_shout_params 
    params.require(:text_shout).permit(:body)
  end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]


  def show
    @user = User.find_by!(username: params[:id])
    @shouts = @user.shouts.page(params[:page]).per(2) 
    @followers = @user.followers
    @followed_users = @user.followed_users 
  end 

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_sign_in.html.erb
<h1>Sign in</h1>
<%= form_for :session, url: session_path do |form| %>
  <div>
    <%= form.label :username %>
    <%= form.text_field :username, placeholder: "Username" %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password, placeholder: "Password" %>
  </div>
  <div>
    <%= form.submit "Sign in" %>
  </div>
<% end %>

app/views/application/_sign_up.html.erb
<%= form_for user do |form| %>

  <% if user.errors.any? %>
    <%= pluralize(user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :username %>
    <%= form.email_field :username %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/dashboards/show.html.erb
<h1>Dashboard</h1> 

<%= form_for(@text_shout) do |form| %>
  <%= form.text_field :body %>
  <%= form.submit "Shout" %>
<% end %>

<%= form_for(@photo_shout) do |form| %>
  <%= form.file_field :image %>
  <%= form.submit "Shout" %>
<% end %>

<%= render @timeline %> 
<%= paginate @timeline %> 

app/views/homes/show.html.erb
<div id="home">
  <header>
    <h1>Welcome to Shoutr</h1>
    <p>Yoo!! Start Shouting!!</p>
  </header>

  <div class="home-forms">
    <div class="home-form">
      <%= render "sign_in" %>
    </div>
    <div class="home-form">
      <%= render "sign_up", user: @user %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tshoutr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= form_for(:search, url: search_path, method: :get) do |form| %>
  <%= form.text_field :query %>
  <%= form.submit "Search" %>
<% end %> 

<% if signed_in? %>
  Welcome <%= current_user.username %> 
  <%= link_to "Sign out", session_path, method: :delete %>
<% else %>
  <%= link_to "Sign in", new_session_path %>
  <%= link_to "Sign up", new_user_path %>
<% end %>
<%= yield %>

</body>
</html>

app/views/photo_shouts/_photo_shout.html.erb
<%= image_tag(photo_shout.image) %> 

app/views/searches/show.html.erb
<h1>Results for <%= @query %></h1> 

<%= render @results %>

app/views/shouts/_shout.html.erb
<%= div_for(shout) do %>
  <%= render shout.content %> by <%= link_to shout.user.username, shout.user %> 
  <%= time_ago_in_words(shout.created_at) %> ago 
<% end %>

app/views/text_shouts/_text_shout.html.erb
<%= text_shout.body %> 

app/views/users/_follow_button.html.erb
<% if @user != current_user %>
  <div>
    <% if current_user.following?(user) %>
      <%= button_to "Unfollow", follow_user_path(user), method: :delete %>
    <% else %>
      <%= button_to "Follow", follow_user_path(user) %>
    <% end %>
  </div>
<% end %>

app/views/users/_user.html.erb
<%= link_to user.username, user %>

app/views/users/new.html.erb
<%= render "sign_up", user: @user %> 

app/views/users/show.html.erb
<h1><%= @user.username %>'s Shouts</h1>

<% if signed_in? %>
  <% if current_user.following?(@user) %>
    <%= button_to "Unfollow", unfollow_user_path(@user), method: :delete %> 
  <% else %>
    <%= button_to "Follow", follow_user_path(@user) %> 
  <% end %>
<% end %> 

<h1>Followers</h1>
<% @followers.each do |follower| %> 
  <%= link_to follower.username, follower %>
<% end %>

<h1>Followed Users</h1>
<% @followed_users.each do |followed_user| %> 
  <%= link_to follower.username, followed_user %>
<% end %>


<%= render @shouts %> 
<%= paginate @shouts %>user